### ISSUE TITLE
Publishing error when a project got newly created

### ISSUE THREAD

**Issue by gabrielwalt** [Adobe-Marketing-Cloud/aem-eclipse-developer-tools#44] opened 2015-03-06 22:24 UTC
After a project is newly created, following error is shown.

![publishing-error](https://cloud.githubusercontent.com/assets/130083/6537509/9baf307a-c414-11e4-908e-c9d6be64ba8c.png)

```
[March 6, 2015 2:38:01 PM MST] InstallLocalBundle -> /Users/gwalt/Documents/workspace/lab/it.tests/target/classes : FAILED (23 ms)
org.apache.sling.ide.osgi.OsgiClientException: Unable to install/update bundle from dir /Users/gwalt/Documents/workspace/lab/it.tests/target/classes : Unresolved constraint in bundle org.summit.lab.it.tests [440]: Unable to resolve 440.0: missing requirement [440.0] osgi.wiring.package; (&(osgi.wiring.package=org.apache.sling.junit.annotations)(version>=1.0.0)(!(version>=2.0.0)))
	at org.apache.sling.ide.osgi.impl.HttpOsgiClient$LocalBundleInstaller.installBundle(HttpOsgiClient.java:216)
	at org.apache.sling.ide.osgi.impl.HttpOsgiClient.installLocalBundle(HttpOsgiClient.java:172)
	at org.apache.sling.ide.osgi.impl.TracingOsgiClient.logInstallLocalBundle(TracingOsgiClient.java:75)
	at org.apache.sling.ide.osgi.impl.TracingOsgiClient.installLocalBundle(TracingOsgiClient.java:57)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishBundleModule(SlingLaunchpadBehaviour.java:339)
	at org.apache.sling.ide.eclipse.core.internal.SlingLaunchpadBehaviour.publishModule(SlingLaunchpadBehaviour.java:219)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModule(ServerBehaviourDelegate.java:1091)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publishModules(ServerBehaviourDelegate.java:1183)
	at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:137)
	at org.eclipse.wst.server.core.model.ServerBehaviourDelegate.publish(ServerBehaviourDelegate.java:774)
	at org.apache.sling.ide.eclipse.core.internal.ServerBehaviourDelegateWithModulePublishSupport.publish(ServerBehaviourDelegateWithModulePublishSupport.java:54)
	at org.eclipse.wst.server.core.internal.Server.publishImpl(Server.java:3157)
	at org.eclipse.wst.server.core.internal.Server$PublishJob.run(Server.java:345)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
```

**Comment by rombert** [comment] 2015-03-06 22:53
Dupe of #3 . You can build from git using `mvn clean verify` to get the latest bits. Hopefully I'll be able to deploy 1.0.4 next week to push all the recent fixes

**Closed by rombert** 2015-03-06 22:53 UTC
Labels: bug
